# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Mercy"
email: merswaf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Certified CURIOUS.Always trying to learn
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://merswaf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: merswaf/merswaf.github.io
twitter: merswaf
github: merswaf

header_image: assets/seb.jpeg


comments: true
disqus: purelog-jekyll

author: Mercy Wafula
author_bio: >-
  Heya! 😄 I’m Mercy, and this is where I share what I’m working on, what I’ve accomplished (hello, certifications!), and whatever else catches my interest. So, welcome — I guess?
  When I’m not extremely lazy, I write up my adventures on Hack The Box, TryHackMe, and CyberDefenders. Feel free to check them out [Here](https://medium.com/@mercysitialo)
author_pic: assets/seb.p
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Mercy Wafula
      avatar: assets/seb.png
  - scope:
      path: ""
      type: project
    values:
      layout: project-entry
      content-type: project

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /projects/:title
  #notes:
   # output: true
    #permalink: /notes/:title
  #projgg:
   # output: true
    #permalink: /jrnals/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
